# Generated by Django 3.1.7 on 2021-04-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Surname',
            new_name='LastName',
        ),
    ]
