# Generated by Django 3.1.7 on 2021-04-12 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20210411_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadvideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
                ('catagory', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('dis', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userinfo')),
            ],
        ),
    ]
