# Generated by Django 3.2 on 2021-04-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='likes',
            field=models.ManyToManyField(related_name='liked_users', to='my_app.Userinfo'),
        ),
    ]
