# Generated by Django 3.2 on 2021-04-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_uploadvideo_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='total_likes',
        ),
    ]
