# Generated by Django 3.2 on 2021-04-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_rename_fname_contact_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
