# Generated by Django 3.2 on 2021-04-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_userinfo_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
