# Generated by Django 3.2 on 2021-04-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_uploadvideo_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('user', models.ManyToManyField(related_name='report_users', to='my_app.Userinfo')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.uploadvideo')),
            ],
        ),
    ]
