# Generated by Django 3.2 on 2021-04-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_video_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userinfo')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.uploadvideo')),
            ],
        ),
    ]
